# Bakeoff Pipeline

**Anna Norberg 2017**
\vspace{5mm}

Bakeoff is a pipeline for fitting various single and joint species distribution models to community data.
The main script used is 'pipeline.m', which guides the user through fitting the models and producing predictions 
based on validation data. All the material are available in Github: AnnaNorb/bakeoff. For the pipeline to run smoothly, 
the required folder structure is created as a part of the pipeline to the location indicated by the user. 

This documentation is for the method HMSC, which works in Matlab environment.
\vspace{10mm}

**1 Preparations**
The published version 2.0 is included in the pipeline, but if the user wishes to use the most recent version,
it can be downloaded form the developer webpage: https://www.helsinki.fi/en/researchgroups/metapopulation-research-centre/hmsc

First clear the workspace.
```
clearvars;
```

Then define the directory of the pipeline.
```
wdpath=fullfile('...','bakeoff','pipeline');
```

Run settings.
```
bakeoffSettings=fullfile(wdpath,'SCRIPTS','settingsHMSCmatlab.m');
```
Then fit the models and produce predictions.
```
for s=1:nsets
    
    for dsz=1:2

        run(fullfile(wdpath,'MODELS','fits_preds_spat.m'))
        run(bakeoffSettings)
        run(fullfile(wdpath,'MODELS','fits_preds_spat_ss.m'))
        run(bakeoffSettings)
        run(fullfile(wdpath,'PREDICT','predmods.m'))
        run(bakeoffSettings)
        run(fullfile(wdpath,'PREDICT','predmods_ss.m'))

    end
end
```



